FROM node:18-alpine

# Working directory
WORKDIR /app

# Copy package.json and package-lock.json 1 level up
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY ../ ./

# Expose port that will be passed as an environment variable
EXPOSE $PORT

# Command to start the application
CMD ["npm", "run", "dev"]
